name: deploy-to-web
run-name: Deploying application to web
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Make build directory
        run: |
          mkdir build && cd build
          
      - name: Install Emscripten
        uses: lovasoa/setup-emscripten@master

      - name: Compile WASM/JS/HTML
        run: emcmake cmake .. && make
