name: deploy-to-web
run-name: Deploying application to web
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Verify project files (DEBUG)
        run: |
          ls -a

      - name: Make build directory
        run: |
          mkdir build && cd build

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v13

      - name: Verify Emscripten install (DEBUG)
        run: |
          emcc -v

      - name: Verify CMake version (DEBUG)
        run: |
          cmake --version

      - name: Compile WASM/JS/HTML
        run: emcmake cmake .. && make
