name: deploy-to-web
run-name: Deploying application to web
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v13

      - name: Compile WASM/JS/HTML
        run: mkdir build && emcmake cmake -B build && cd build && make

      - name: Install doctl (to access digital ocean api)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: hydrogax/kloenk
          tag_with_ref: true
          tag_with_sha: true

      # - name: Create Droplet and Deploy
        # run: doctl compute droplet create "$GIT_TAG_NAME" --image docker-18-04 s-1vcpu --region nyc1 --user-data-file deploy.sh --wait

